-- MySQL Script generated by MySQL Workbench
-- Sun Apr 12 17:21:40 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ASSET_SIRIUS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ASSET_SIRIUS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ASSET_SIRIUS` DEFAULT CHARACTER SET utf8 ;
USE `ASSET_SIRIUS` ;

-- -----------------------------------------------------
-- Table `ASSET_SIRIUS`.`segmento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ASSET_SIRIUS`.`segmento` (
  `id_segmento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id_segmento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ASSET_SIRIUS`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ASSET_SIRIUS`.`cliente` (
  `id_cliente` BIGINT NOT NULL AUTO_INCREMENT,
  `fk_segmento` INT NOT NULL,
  `cpf_cnpj` VARCHAR(20) NULL,
  `nome` VARCHAR(100) NULL,
  `perfil_risco` VARCHAR(30) NULL,
  `tipo_investidor` VARCHAR(45) NULL,
  `data_cadastro` DATETIME NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_cliente_segmento1_idx` (`fk_segmento` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_segmento1`
    FOREIGN KEY (`fk_segmento`)
    REFERENCES `ASSET_SIRIUS`.`segmento` (`id_segmento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ASSET_SIRIUS`.`gerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ASSET_SIRIUS`.`gerente` (
  `id_gerente` BIGINT NOT NULL AUTO_INCREMENT,
  `fk_segmento` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`id_gerente`),
  INDEX `fk_gerente_segmento1_idx` (`fk_segmento` ASC) VISIBLE,
  CONSTRAINT `fk_gerente_segmento1`
    FOREIGN KEY (`fk_segmento`)
    REFERENCES `ASSET_SIRIUS`.`segmento` (`id_segmento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ASSET_SIRIUS`.`cliente_gerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ASSET_SIRIUS`.`cliente_gerente` (
  `id_cliente_gerente` BIGINT NOT NULL AUTO_INCREMENT,
  `cliente_id_cliente` BIGINT NOT NULL,
  `gerente_id_gerente` BIGINT NOT NULL,
  `data_inicio` DATETIME NULL,
  `data_fim` DATETIME NULL,
  PRIMARY KEY (`id_cliente_gerente`, `cliente_id_cliente`, `gerente_id_gerente`),
  INDEX `fk_cliente_gerente_cliente1_idx` (`cliente_id_cliente` ASC) VISIBLE,
  INDEX `fk_cliente_gerente_gerente1_idx` (`gerente_id_gerente` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_gerente_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `ASSET_SIRIUS`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_gerente_gerente1`
    FOREIGN KEY (`gerente_id_gerente`)
    REFERENCES `ASSET_SIRIUS`.`gerente` (`id_gerente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ASSET_SIRIUS`.`fundo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ASSET_SIRIUS`.`fundo` (
  `id_registro_fundo` BIGINT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(15) NULL,
  `denominacao_social` VARCHAR(100) NULL,
  `gestor` VARCHAR(100) NULL,
  `cnpj_gestor` VARCHAR(15) NULL,
  `administrador` VARCHAR(100) NULL,
  `cnpj_administrador` VARCHAR(15) NULL,
  `tipo_fundo` VARCHAR(15) NULL,
  `data_constituicao` DATE NULL,
  `data_registro` DATE NULL,
  `codigo_cvm` INT(7) NULL,
  `data_cancelamento` DATE NULL,
  `situacao` VARCHAR(100) NULL,
  `data_inicio_situacao` DATE NULL,
  `is_proprio` CHAR(1) NULL,
  PRIMARY KEY (`id_registro_fundo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ASSET_SIRIUS`.`gestor_fundo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ASSET_SIRIUS`.`gestor_fundo` (
  `id_gestor_fundo` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`id_gestor_fundo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ASSET_SIRIUS`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ASSET_SIRIUS`.`usuario` (
  `id_usuario` BIGINT NOT NULL AUTO_INCREMENT,
  `fk_gerente` BIGINT NOT NULL,
  `fk_gestor_fundo` BIGINT NOT NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `is_adm` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_gerente1_idx` (`fk_gerente` ASC) VISIBLE,
  INDEX `fk_usuario_gestor_fundo1_idx` (`fk_gestor_fundo` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_gerente1`
    FOREIGN KEY (`fk_gerente`)
    REFERENCES `ASSET_SIRIUS`.`gerente` (`id_gerente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_gestor_fundo1`
    FOREIGN KEY (`fk_gestor_fundo`)
    REFERENCES `ASSET_SIRIUS`.`gestor_fundo` (`id_gestor_fundo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ASSET_SIRIUS`.`classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ASSET_SIRIUS`.`classe` (
  `id_registro_classe` BIGINT NOT NULL AUTO_INCREMENT,
  `fk_registro_fundo` BIGINT NOT NULL,
  `cnpj` VARCHAR(15) NULL,
  `id_registro_fundo` BIGINT NULL,
  `tipo_classe` VARCHAR(100) NULL,
  `denominacao_social` VARCHAR(100) NULL,
  `classificacao` VARCHAR(100) NULL,
  `auditor` VARCHAR(100) NULL,
  `custodiante` VARCHAR(100) NULL,
  `controlador` VARCHAR(100) NULL,
  `classificacao_anbima` VARCHAR(100) NULL,
  `indicador_desempenho` VARCHAR(100) NULL,
  `is_proprio` CHAR(1) NULL,
  PRIMARY KEY (`id_registro_classe`),
  INDEX `fk_classe_fundo1_idx` (`fk_registro_fundo` ASC) VISIBLE,
  CONSTRAINT `fk_classe_fundo1`
    FOREIGN KEY (`fk_registro_fundo`)
    REFERENCES `ASSET_SIRIUS`.`fundo` (`id_registro_fundo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ASSET_SIRIUS`.`subclasse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ASSET_SIRIUS`.`subclasse` (
  `id_subclasse` BIGINT NOT NULL AUTO_INCREMENT,
  `id_registro_classe` BIGINT NOT NULL,
  `codigo_cvm` INT(7) NULL,
  `denominacao_social` VARCHAR(100) NULL,
  `situacao` VARCHAR(100) NULL,
  `publico_alvo` VARCHAR(100) NULL,
  `previdenciario` CHAR(1) NULL,
  `is_proprio` CHAR(1) NULL,
  INDEX `fk_subclasse_classe1_idx` (`id_registro_classe` ASC) VISIBLE,
  PRIMARY KEY (`id_subclasse`),
  CONSTRAINT `fk_subclasse_classe1`
    FOREIGN KEY (`id_registro_classe`)
    REFERENCES `ASSET_SIRIUS`.`classe` (`id_registro_classe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ASSET_SIRIUS`.`informe_diario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ASSET_SIRIUS`.`informe_diario` (
  `id_patrimonio_liquido` BIGINT NOT NULL AUTO_INCREMENT,
  `data_competencia` DATE NOT NULL,
  `fk_subclasse` BIGINT NULL,
  `fk_registro_classe` BIGINT NULL,
  `fundo_id_registro_fundo` BIGINT NULL,
  `valor_patrimonio_liquido` DECIMAL(19,2) NULL,
  `quantidade_cotista` BIGINT NULL,
  `valor_cota` DECIMAL(19,2) NULL,
  `captacao` DECIMAL(19,2) NULL,
  `resgate` DECIMAL(19,2) NULL,
  `data_insercao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  PRIMARY KEY (`id_patrimonio_liquido`, `data_competencia`),
  INDEX `fk_informe_diario_subclasse1_idx` (`fk_subclasse` ASC) VISIBLE,
  INDEX `fk_informe_diario_classe1_idx` (`fk_registro_classe` ASC) VISIBLE,
  INDEX `fk_informe_diario_fundo1_idx` (`fundo_id_registro_fundo` ASC) VISIBLE,
  CONSTRAINT `fk_informe_diario_subclasse1`
    FOREIGN KEY (`fk_subclasse`)
    REFERENCES `ASSET_SIRIUS`.`subclasse` (`id_subclasse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_informe_diario_classe1`
    FOREIGN KEY (`fk_registro_classe`)
    REFERENCES `ASSET_SIRIUS`.`classe` (`id_registro_classe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_informe_diario_fundo1`
    FOREIGN KEY (`fundo_id_registro_fundo`)
    REFERENCES `ASSET_SIRIUS`.`fundo` (`id_registro_fundo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ASSET_SIRIUS`.`fundo_cotista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ASSET_SIRIUS`.`fundo_cotista` (
  `id_fundo_cotista` BIGINT NOT NULL AUTO_INCREMENT,
  `fk_registro_classe` BIGINT NOT NULL,
  `fk_subclasse` BIGINT NOT NULL,
  `fk_cliente` BIGINT NOT NULL,
  `data_inicio` DATE NULL,
  `quantidade_cotas` DECIMAL(17,3) NULL,
  INDEX `fk_fundo_cotista_cliente1_idx` (`fk_cliente` ASC) VISIBLE,
  PRIMARY KEY (`id_fundo_cotista`, `fk_cliente`),
  INDEX `fk_cotista_classe1_idx` (`fk_registro_classe` ASC) VISIBLE,
  INDEX `fk_cotista_subclasse1_idx` (`fk_subclasse` ASC) VISIBLE,
  CONSTRAINT `fk_fundo_cotista_cliente1`
    FOREIGN KEY (`fk_cliente`)
    REFERENCES `ASSET_SIRIUS`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cotista_classe1`
    FOREIGN KEY (`fk_registro_classe`)
    REFERENCES `ASSET_SIRIUS`.`classe` (`id_registro_classe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cotista_subclasse1`
    FOREIGN KEY (`fk_subclasse`)
    REFERENCES `ASSET_SIRIUS`.`subclasse` (`id_subclasse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ASSET_SIRIUS`.`parametro_alerta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ASSET_SIRIUS`.`parametro_alerta` (
  `id_parametro_alerta` BIGINT NOT NULL AUTO_INCREMENT,
  `fk_registro_classe` BIGINT NULL,
  `fk_subclasse` BIGINT NULL,
  `nome` VARCHAR(45) NULL,
  `valor` VARCHAR(45) NULL,
  PRIMARY KEY (`id_parametro_alerta`),
  INDEX `fk_parametro_alerta_classe1_idx` (`fk_registro_classe` ASC) VISIBLE,
  INDEX `fk_parametro_alerta_subclasse1_idx` (`fk_subclasse` ASC) VISIBLE,
  CONSTRAINT `fk_parametro_alerta_classe1`
    FOREIGN KEY (`fk_registro_classe`)
    REFERENCES `ASSET_SIRIUS`.`classe` (`id_registro_classe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parametro_alerta_subclasse1`
    FOREIGN KEY (`fk_subclasse`)
    REFERENCES `ASSET_SIRIUS`.`subclasse` (`id_subclasse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ASSET_SIRIUS`.`aplicacao_resgate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ASSET_SIRIUS`.`aplicacao_resgate` (
  `id_aplicacao_resgate` BIGINT NOT NULL AUTO_INCREMENT,
  `fk_cliente` BIGINT NOT NULL,
  `fk_classe` BIGINT NULL,
  `fk_subclasse` BIGINT NULL,
  `natureza_operacao` CHAR(1) NULL,
  `valor` DECIMAL(19,2) NULL,
  `data` DATETIME NULL,
  PRIMARY KEY (`id_aplicacao_resgate`),
  INDEX `fk_aplicacao_resgate_classe1_idx` (`fk_classe` ASC) VISIBLE,
  INDEX `fk_aplicacao_resgate_subclasse1_idx` (`fk_subclasse` ASC) VISIBLE,
  INDEX `fk_aplicacao_resgate_cliente1_idx` (`fk_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_aplicacao_resgate_classe1`
    FOREIGN KEY (`fk_classe`)
    REFERENCES `ASSET_SIRIUS`.`classe` (`id_registro_classe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aplicacao_resgate_subclasse1`
    FOREIGN KEY (`fk_subclasse`)
    REFERENCES `ASSET_SIRIUS`.`subclasse` (`id_subclasse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aplicacao_resgate_cliente1`
    FOREIGN KEY (`fk_cliente`)
    REFERENCES `ASSET_SIRIUS`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Criar usuário
CREATE USER 'usr_asset_sirius'@'%' IDENTIFIED BY '123456';

-- Conceder permissões no schema
GRANT ALL PRIVILEGES ON ASSET_SIRIUS.* TO 'usr_asset_sirius'@'%';

-- Aplicar mudanças
FLUSH PRIVILEGES;
